INSERT INTO items (item_name,
                   item_ttrpg,
                   item_weight,
                   item_cost,
                   item_description,
                   item_description_notes,
                   item_source,
                   item_rarity,
                   item_renowned_quality,

                   item_magical,
                   item_requires_attunement,
                   item_is_cursed,
                   item_magic_bonus_plus_1,
                   item_magic_bonus_plus_2,
                   item_magic_bonus_plus_3,
                   item_has_charges,

                   item_number_of_charges,
                   item_weapon_range,
                   item_weapon_damage_calc,
                   item_weapon_damage_type,
                   item_weapon_properties,
                   item_weapon_notes,

                   item_armor_class,
                   item_armor_notes,

                   item_image_url,
                   item_source_id)
VALUES ('Adamantine Breastplate',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
             This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer''s vital organs while leaving the wearer relatively unencumbered.',
        'immunity: critical hits, combat, warding',
        'Immunity: Critical Hits, Combat, Warding',
        'uncommon',
        null,

        true,
        false,
        false,
        false,
        false,
        false,
        null,

        null,
        null,
        null,
        null,
        null,
        null,

        '14+ Dex modifier (max 2)',
        null,

        null,
        17),
       ('Adamantine Chain Shirt ',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer''s upper body and allows the sound of the rings rubbing against one another to be muffled by outer layers.',
        'mmunity: Critical Hits, Combat, Warding',
        null,
        'uncommon',
        true,

        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '13 + Dex modifier (max 2)',
        null,

        null,
        17),
       ('Adamantine Scale Mail',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              This armor consists of a coat and leggings (and perhaps a separate skirt) of leather covered with overlapping pieces of metal, much like the scales of a fish. The suit includes gauntlets.',
        'Immunity: Critical Hits, Combat, Warding, Stealth Disadvantage',
        null,
        'uncommon',
        true,

        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '14 + Dex modifier (max 2)',
        null,

        null,
        17),
       ('Adamantine Half Plate',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              Half plate consists of shaped metal plates that cover most of the wearer''s body. It does not include leg protection beyond simple greaves that are attached with leather straps.',
        'Immunity: Critical Hits, Warding, Stealth Disadvantage',
        null,
        'uncommon',
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '15+ Dex modifier (max 2)',
        null,

        null,
        17),
       ('Adamantine Ring Mail',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              This armor is leather armor with heavy rings sewn into it. The rings help reinforce the armor against blows from swords and axes. Ring mail is inferior to chain mail, and it''s usually worn only by those who can''t afford better armor.',
        'Immunity: Critical Hits, Combat, Warding, Stealth Disadvantage',
        null,
        'uncommon',
        true,

        false,
        false,
        false,
        false,
        false,
        null,
        null,

        null,
        null,
        null,
        null,
        null,
        null,

        '14',
        null,

        null,
        17),
       ('Adamantine Chain Mail ',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets.',
        'Immunity: Critical Hits, Combat, Warding, Str. 13 Required, Stealth Disadvantage',
        null,
        'uncommon',
        true,

        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '16',
        null,

        null,
        17),
       ('Adamantine Plate',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              Plate consists of shaped, interlocking metal plates to cover the entire body. A suit of plate includes gauntlets, heavy leather boots, a visored helmet, and thick layers of padding underneath the armor. Buckles and straps distribute the weight over the body.',
        'Immunity: Critical Hits, Combat, Warding, Str. 15 Required, Stealth Disadvantage',
        null,
        'uncommon',
        true,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '14',
        null,

        null,
        17),
       ('Adamantine Splint',
        'DND5E',
        '20 lb',
        null,
        'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any Critical Hit against you becomes a normal hit.
              This armor is made of narrow vertical strips of metal riveted to a backing of leather that is worn over cloth padding. Flexible chain mail protects the joints.',
        'Immunity: Critical Hits, Combat, Warding, Str. 15 Required, Stealth Disadvantage',
        null,
        null,
        true,

        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        '17',
        null,

        null,
        17),
       ('Wings of Flying',
        'DND5E',
        null,
        null,
        'While wearing this cloak, you can use an action to speak its command word. This turns the cloak into a pair of bat wings or bird wings on your back for 1 hour or until you repeat the command word as an action. The wings give you a flying speed of 60 feet. When they disappear, you cannullt use them again for 1d12 hours.',
        'set: innate speed (flying), movement, outerwear',
        'Dungeon Master’s Guide, pg. 324',
        'rare',
        'Wondrous Item',

        true,
        true,
        false,
        false,
        false,
        true,
        null,
        null,

        null,
        null,
        null,
        null,
        null,

        null,
        null,

        null,
        17)
