INSERT INTO items (
    item_name,
    item_ttrpg,
    item_weight,
    item_cost,
    item_description,
    item_description_notes,
    item_source,
    item_rarity,
    item_renowned_quality,

    item_magical,
    item_requires_attunement,
    item_is_cursed,
    item_magic_bonus_plus_1,
    item_magic_bonus_plus_2,
    item_magic_bonus_plus_3,
    item_has_charges,
    item_number_of_charges,

    item_weapon_range,
    item_weapon_damage_calc,
    item_weapon_damage_type,
    item_weapon_properties,
    item_weapon_notes,

    item_armor_class,
    item_armor_notes,

    item_image_url,
    item_source_id)
VALUES(
          'Scale, Merchant''s',
          'DND5E',
          '3 lbs',
          '5 gp',
          'A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.',
          null,
          'Basic Rules (2014)',
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Tent, Two-Person',
          'DND5E',
          '20 lbs',
          '2 gp',
          null,
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Bottle, Glass',
          'DND5E',
          '2 lbs',
          '2 gp',
          'A bottle can hold 1 1/2 pints of liquid.',
          null,
          'Basic Rules (2014)',
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Pick, Miner''s',
          'DND5E',
          '10 lbs',
          '2 gp',
          'A miner''s pick is designed to concentrate the force of its blow on a small area.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Saddle, Pack',
          'DND5E',
          '15 lbs',
          '5 gp',
          'A standard saddle for a pack mount.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,

          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Spikes, Iron (10)',
          'DND5E',
          '5 lbs',
          '1 gp',
          'Standard iron spikes typically used with a hammer.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Lamp',
          'DND5E',
          '1 lb',
          '5 sp',
          'A Lamp burns Oil as fuel to cast Bright Light in a 15-foot radius and Dim Light for an additional 30 feet.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,,
          null,

          null,
          null,

          null,
          53
      ),
      (
          'Ball Bearings',
          'DND5E',
          '2 lbs',
          '1 gp',
          'As a Utilize action, you can spill Ball Bearings from their pouch. They spread to cover a level, 10-foot-square area within 10 feet of yourself. A creature that enters this area for the first time on a turn must succeed on a DC 10 Dexterity saving throw or have the Prone condition. It takes 10 minutes to recover the Ball Bearings.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      )
