INSERT INTO items (
    item_name,
    item_ttrpg,
    item_weight,
    item_cost,
    item_description,
    item_description_notes,
    item_source,
    item_rarity,
    item_renowned_quality,

    item_magical,
    item_requires_attunement,
    item_is_cursed,
    item_magic_bonus_plus_1,
    item_magic_bonus_plus_2,
    item_magic_bonus_plus_3,
    item_has_charges,
    item_number_of_charges,

    item_weapon_range,
    item_weapon_damage_calc,
    item_weapon_damage_type,
    item_weapon_properties,
    item_weapon_notes,

    item_armor_class,
    item_armor_notes,

    item_image_url,
    item_source_id)
VALUES(
          'Scale, Merchant''s',
          'DND5E',
          '3 lbs',
          '5 gp',
          'A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.',
          null,
          'Basic Rules (2014)',
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Tent, Two-Person',
          'DND5E',
          '20 lbs',
          '2 gp',
          null,
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Bottle, Glass',
          'DND5E',
          '2 lbs',
          '2 gp',
          'A bottle can hold 1 1/2 pints of liquid.',
          null,
          'Basic Rules (2014)',
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Pick, Miner''s',
          'DND5E',
          '10 lbs',
          '2 gp',
          'A miner''s pick is designed to concentrate the force of its blow on a small area.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Saddle, Pack',
          'DND5E',
          '15 lbs',
          '5 gp',
          'A standard saddle for a pack mount.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,

          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Spikes, Iron (10)',
          'DND5E',
          '5 lbs',
          '1 gp',
          'Standard iron spikes typically used with a hammer.',
          null,
          null,
          'common',
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Lamp',
          'DND5E',
          '1 lb',
          '5 sp',
          'A Lamp burns Oil as fuel to cast Bright Light in a 15-foot radius and Dim Light for an additional 30 feet.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          53
      ),
      (
          'Ball Bearings',
          'DND5E',
          '2 lbs',
          '1 gp',
          'As a Utilize action, you can spill Ball Bearings from their pouch. They spread to cover a level, 10-foot-square area within 10 feet of yourself. A creature that enters this area for the first time on a turn must succeed on a DC 10 Dexterity saving throw or have the Prone condition. It takes 10 minutes to recover the Ball Bearings.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Soap',
          'DND5E',
          null,
          '2 cp',
          'A commodity used for bathing.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Saddle, Military',
          'DND5E',
          '30 lbs',
          '20 gp',
          'A military saddle braces the rider, helping you keep your seat on an active mount in battle. It gives you advantage on any check you make to remain mounted.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Flask or Tankard',
          'DND5E',
          '1 lb',
          '2 cp',
          'A flask or tankard can hold 1 pint of liquid.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Rope Silk (50 feet)',
          'DND5E',
          '5 lbs',
          '10 gp',
          'Rope, has 2 hit points and can be burst with a DC 17 Strength check.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Basket',
          'DND5E',
          null,
          null,
          null,
          null,
          null,
          null,
          null,

          null,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          5
      ),
      (
          'Backpack',
          'DND5E',
          '5 lb',
          '2 gp',
          'A backpack is a leather pack carried on the back, typically with straps to secure it. A backpack can hold 1 cubic foot/ 30 pounds of gear.
                You can also strap items, such as a bedroll or a coil of rope, to the outside of a backpack.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
          'Pole (10-foot)',
          'DND5E',
          '7 lb',
          '10 sp',
          'When you suspect a trap, you can put the end of your 10-foot pole through that hole in the wall instead of reaching in with your hand.',
          null,
          null,
          null,
          null,

          false,
          false,
          false,
          false,
          false,
          false,
          false,
          null,

          null,
          null,
          null,
          null,
          null,

          null,
          null,

          null,
          5
      ),
      (
       'Bag of Holding',
       'DND5E',
       '5 lb',
       null,
       'This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. The bag weighs 15 pounds, regardless of its contents. Retrieving an item from the bag requires an action.
            If the bag is overloaded, pierced, or torn, it ruptures and is destroyed, and its contents are scattered in the Astral Plane. If the bag is turned inside out, its contents spill forth, unharmed, but the bag must be put right before it can be used again. Breathing creatures inside the bag can survive up to a number of minutes equal to 10 divided by the number of creatures (minimum 1 minute), after which time they begin to suffocate.
            Placing a bag of holding inside an extradimensional space created by a handy haversack, portable hole, or similar item instantly destroys both items and opens a gate to the Astral Plane. The gate originates where the one item was placed inside the other. Any creature within 10 feet of the gate is sucked through it to a random location on the Astral Plane. The gate then closes. The gate is one-way only and can’t be reopened.
            *Capacity:* 500lb.',
       'Utility, Container',
       'Dungeon Master’s Guide, pg. 234',
       'uncommon',
       'Wondrous Item',

       true,
       false,
       false,
       false,
       false,
       false,
       false,
       null,

       null,
       null,
       null,
       null,
       null,

       null,
       null,

       null,
       17
      )
