INSERT INTO characters
(
    character_name,
    character_level,
    character_active_level,
    character_species,
    character_classes,
    character_background_summary,
    character_full_hp,
    character_current_hp,
    character_ac,
    character_initiative,
    character_hit_dice,
    character_proficiency,
    character_bonus,
    character_ability_saves,
    character_xp,

    attribute_strength,
    attribute_strength_mod,
    attribute_dexterity,
    attribute_dexterity_mod,
    attribute_constitution,
    attribute_constitution_mod,
    attribute_intelligence,
    attribute_intelligence_mod,
    attribute_wisdom,
    attribute_wisdom_mod,
    attribute_charisma,
    attribute_charisma_mod,

    skill_acrobatics,
    skill_acrobatics_prof,
    skill_animal_handling,
    skill_animal_handling_prof,
    skill_arcana,
    skill_arcana_prof,
    skill_athletics,
    skill_athletics_prof,
    skill_deception,
    skill_deception_prof,
    skill_history,
    skill_history_prof,
    skill_insight,
    skill_insight_prof,
    skill_intimidation,
    skill_intimidation_prof,
    skill_investigation,
    skill_investigation_prof,
    skill_medicine,
    skill_medicine_prof,
    skill_nature,
    skill_nature_prof,
    skill_perception,
    skill_perception_prof,
    skill_performance,
    skill_performance_prof,
    skill_persuasion,
    skill_persuasion_prof,
    skill_religion,
    skill_religion_prof,
    skill_sleight_of_hand,
    skill_sleight_of_hand_prof,
    skill_stealth,
    skill_stealth_prof,
    skill_survival,
    skill_survival_prof,

    proficiencies_armor,
    proficiencies_weapons,
    proficiencies_tools,
    proficiencies_languages,

    saving_throws_str,
    saving_throws_str_prof,
    saving_throws_dex,
    saving_throws_dex_prof,
    saving_throws_con,
    saving_throws_con_prof,
    saving_throws_int,
    saving_throws_int_prof,
    saving_throws_wis,
    saving_throws_wis_prof,
    saving_throws_cha,
    saving_throws_cha_prof,
    saving_throws_notes,

    senses_passive_perception,
    senses_passive_investigation,
    senses_passive_insight,
    senses_notes,

    defenses
)

VALUES ('Roskat',
        3,
        true,
        'Procyon',
        'Rogue 1, Druid 2',
        'Haunted One',
        24,
        24,
        12,
        '+2',
        '1d8 + 1d8',
        '+2',
        '+2',
        '-',
        'Milestone',

        10,
        '+0',
        14,
        '+2',
        15,
        '+2',
        12,
        '+1',
        16,
        '+3',
        13,
        '+1',

        '+4',
        'proficient',
        '+3',
        'not proficient',
        '+6',
        'proficient',
        '+0',
        'not proficient',
        '+1',
        'not proficient',
        '+1',
        'not proficient',
        '+5',
        'proficient',
        '+1',
        'not proficient',
        '+1',
        'not proficient',
        '+3',
        'not  proficient',
        '+4',
        'not proficient',
        '+3',
        'not proficient',
        '+1',
        'not proficient',
        '+1',
        'not proficient',
        '+1',
        'not proficient',
        '+6',
        'expert',
        '+6',
        'expert advantage',
        '+5',
        'proficient',

        'Light Armor, Shields',
        'Crossbow, Hand, Rapier, Scimitar, Shortsword, Simple Weapons, Whip',
        'Thieves'' Tools, Tinker''s Tools',
        'Abyssal, Celestial, Cervan, Druidic, Mapach, Primordial, Thieves’ Cant',

        '+0',
        false,
        '+4',
        true,
        '+2',
        false,
        '+3',
        true,
        '+3',
        false,
        '+1',
        false,
        'advantage poison saves',

        13,
        11,
        15,
        'Darkvision 60 ft.',

        'poison resistance'
       )
