INSERT INTO character_unique_items(
                            character_id,
                            item_name,
                            item_weight,
                            item_cost,
                            item_quantity,
                            item_location,
                            item_notes,
                            item_source,
                            item_types,
                            item_commonality,
                            item_magical,

                            item_weapon_attack_type,
                            item_weapon_range,
                            item_weapon_damage,
                            item_weapon_damage_type,
                            item_weapon_properties,
                            item_weapon_type,
                            item_weapon_notes,

                            item_armor_class,
                            item_armor_type,
                            item_armor_notes,

                            item_attached_spells,
                            item_tags,
                            item_image_url
)

VALUES
       (
           1,
           'Bag of Shiny Rocks',
           '1/4 lb',
           '-',
           '1',
           'pocket',
           'Small bag of shiny smooth rocks collected from home. Sentimental value.',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Half burnt incense',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Red thread and needle',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: 1 foot long red thread tied to a swwing needle',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Sword Stick',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A small palm size stick in the shape of a sword',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Black Feather',
           '-',
           '-',
           '1',
           'poket',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Polished rocks',
           '-',
           '-',
           '8',
           'pocket',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Crossbow bolt',
           '-',
           '-',
           '1',
           'quiver',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Fabric',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Fabric from a plaid shirt, with a blood stain on it',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Plaster Chips',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Small bits of plaster chips',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Vile of liquid',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A vial filled with a clear green liquid',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Bridle Bit',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Amber Glass',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Amber piece of glass',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'thimble',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Thimble with a dent, engraved with a single tiny star',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'spool',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Spool that is empty of thread',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'broom straw',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: Unused broom straw ',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Tea tin',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Sandal',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A child''s sandal',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Beeswax',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A small ball of beeswax',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Sage',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A bundle of sage',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Mirror',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A small hand mirror set in ivory',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'rod',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up: A rod of cold (wrought) iron',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       )
