INSERT INTO character_unique_items(
                            character_id,
                            item_name,
                            item_weight,
                            item_cost,
                            item_quantity,
                            item_location,
                            item_notes,
                            item_source,
                            item_types,
                            item_commonality,
                            item_magical,

                            item_weapon_attack_type,
                            item_weapon_range,
                            item_weapon_damage,
                            item_weapon_damage_type,
                            item_weapon_properties,
                            item_weapon_type,
                            item_weapon_notes,

                            item_armor_class,
                            item_armor_type,
                            item_armor_notes,

                            item_attached_spells,
                            item_tags,
                            item_image_url
)

VALUES
       (
           1,
           'Bag of Shiny Rocks',
           '1/4 lb',
           '-',
           '1',
           'pocket',
           'Small bag of shiny smooth rocks collected from home. Sentimental value.',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           'Half burnt incense',
           '-',
           '-',
           '1',
           'pocket',
           'Blind Pick Up',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),
       (
           1,
           '',
           '-',
           '-',
           '',
           '',
           '',
           'homebrew',
           'random pick',
           'common',
           false,

           '',
           '',
           '',
           '',
           '',
           '',
           '',

           '',
           '',
           '',
           '',

           'personal',
           ''
       ),

