
const Raveen = () => {
    return {
        // Static
        cName: "Raveen",
        cPix: "https://i.pinimg.com/564x/9e/5f/90/9e5f9074e1378adbc460f31616c0dbaf.jpg",
        cSpecies: "Human",
        cClass: "Bard-8 Sor-1",
        cBackground: "Criminal, Spy",
        cHP: "88",
        cAC: "15",
        cMovement: "Walk 45",
        cInitiative: "+4",
        cHitDice: "8d8 + 1d6",
        cProfBonus: "+4",
        cAbilitySaveDC: "-",
        cXP: "Milestone",
        cLevel: 9,
        // Main Stats
        cStr: 9,
        cStrMod: "-1",
        cDex: 15,
        cDexMod: "+2",
        cCon: 15,
        cConMod: "+2",
        cInt: 15,
        cIntMod: "+2",
        cWis: 14,
        cWisMod: "+2",
        cCha: 16,
        cChaMod: "+3",
        // Skills
        cSkillAcrobaticsProf: "full",
        cSkillAcrobaticsBonus: "+6",
        cSkillAnimalHandlingProf: "half",
        cSkillAnimalHandlingBonus: "+4",
        cSkillArcanaProf: "half",
        cSkillArcanaBonus: "+4",
        cSkillAthleticsProf: "half",
        cSkillAthleticsBonus: "+1",
        cSkillDeceptionProf: "full",
        cSkillDeceptionBonus: "+7",
        cSkillHistoryProf: "half",
        cSkillHistoryBonus: "+4",
        cSkillInsightProf: "half",
        cSkillInsightBonus: "+4",
        cSkillIntimidationProf: "half",
        cSkillIntimidationBonus: "+5",
        cSkillInvestigationProf: "full",
        cSkillInvestigationBonus: "+6",
        cSkillMedicineProf: "half",
        cSkillMedicineBonus: "+4",
        cSkillNatureProf: "half",
        cSkillNatureBonus: "+4",
        cSkillPerceptionProf: "expert",
        cSkillPerceptionBonus: "+10",
        cSkillPerformanceProf: "full",
        cSkillPerformanceBonus: "+7",
        cSkillPersuasionProf: "full",
        cSkillPersuasionBonus: "+7",
        cSkillReligionProf: "half",
        cSkillReligionBonus: "+4",
        cSkillSlightOfHandProf: "full",
        cSkillSlightOfHandBonus: "+6",
        cSkillStealthProf: "expert",
        cSkillStealthBonus: "+10",
        cSkillSurvivalProf: "half",
        cSkillSurvivalBonus: "+4",
        cSkillsAdditional: "",
        // Saving Throws
        cSavingThrowStrPro: false,
        cSavingThrowsStr: "-1",
        cSavingThrowDexPro: true,
        cSavingThrowsDex: "+6",
        cSavingThrowConPro: false,
        cSavingThrowsCon: "+2",
        cSavingThrowIntPro: false,
        cSavingThrowsInt: "+2",
        cSavingThrowWisPro: false,
        cSavingThrowsWis: "+2",
        cSavingThrowChaPro: true,
        cSavingThrowsCha: "+7",
        // Passive Senses
        cPassiveSensesPerception: "20",
        cPassiveSensesInvestigation: "16",
        cPassiveSensesInsight: "14",
    }
}

export default Raveen()