CREATE SEQUENCE character_seq start 1;

CREATE TABLE characters (
                            character_id SERIAL PRIMARY KEY,
                            character_name VARCHAR(100) NOT NULL,
                            character_level INT NOT NULL,
                            character_active_level BOOLEAN NOT NULL,
                            character_species VARCHAR(100) NOT NULL,
                            character_classes VARCHAR(255),
                            character_background_summary VARCHAR(255),
                            character_full_hp INT,
                            character_current_hp INT,
                            character_ac INT,
                            character_initiative VARCHAR(10),
                            character_hit_dice VARCHAR(10),
                            character_proficiency VARCHAR(10),
                            character_bonus VARCHAR(10),
                            character_ability_saves VARCHAR(10),
                            character_xp VARCHAR(255),

                            attribute_strength INT,
                            attribute_strength_mod VARCHAR(10),
                            attribute_dexterity INT,
                            attribute_dexterity_mod VARCHAR(10),
                            attribute_constitution INT,
                            attribute_constitution_mod VARCHAR(10),
                            attribute_intelligence INT,
                            attribute_intelligence_mod VARCHAR(10),
                            attribute_wisdom INT,
                            attribute_wisdom_mod VARCHAR(10),
                            attribute_charisma INT,
                            attribute_charisma_mod VARCHAR(10),

                            skill_acrobatics VARCHAR(10),
                            skill_acrobatics_prof VARCHAR(10),
                            skill_animal_handling VARCHAR(10),
                            skill_animal_handling_prof VARCHAR(10),
                            skill_arcana VARCHAR(10),
                            skill_arcana_prof VARCHAR(10),
                            skill_athletics VARCHAR(10),
                            skill_athletics_prof VARCHAR(10),
                            skill_deception VARCHAR(10),
                            skill_deception_prof VARCHAR(10),
                            skill_history VARCHAR(10),
                            skill_history_prof VARCHAR(10),
                            skill_insight VARCHAR(10),
                            skill_insight_prof VARCHAR(10),
                            skill_intimidation VARCHAR(10),
                            skill_intimidation_prof VARCHAR(10),
                            skill_investigation VARCHAR(10),
                            skill_investigation_prof VARCHAR(10),
                            skill_medicine VARCHAR(10),
                            skill_medicine_prof VARCHAR(10),
                            skill_nature VARCHAR(10),
                            skill_nature_prof VARCHAR(10),
                            skill_perception VARCHAR(10),
                            skill_perception_prof VARCHAR(10),
                            skill_performance VARCHAR(10),
                            skill_performance_prof VARCHAR(10),
                            skill_persuasion VARCHAR(10),
                            skill_persuasion_prof VARCHAR(10),
                            skill_religion VARCHAR(10),
                            skill_religion_prof VARCHAR(10),
                            skill_sleight_of_hand VARCHAR(10),
                            skill_sleight_of_hand_prof VARCHAR(10),
                            skill_stealth VARCHAR(10),
                            skill_stealth_prof VARCHAR(10),
                            skill_survival VARCHAR(10),
                            skill_survival_prof VARCHAR(10),

                            proficiencies_armor VARCHAR(255),
                            proficiencies_weapons VARCHAR(255),
                            proficiencies_tools VARCHAR(255),
                            proficiencies_languages VARCHAR(255),

                            saving_throws_str VARCHAR(10),
                            saving_throws_str_prof BOOLEAN,
                            saving_throws_dex VARCHAR(10),
                            saving_throws_dex_prof BOOLEAN,
                            saving_throws_con VARCHAR(10),
                            saving_throws_con_prof BOOLEAN,
                            saving_throws_int VARCHAR(10),
                            saving_throws_int_prof BOOLEAN,
                            saving_throws_wis VARCHAR(10),
                            saving_throws_wis_prof BOOLEAN,
                            saving_throws_cha VARCHAR(10),
                            saving_throws_cha_prof BOOLEAN,
                            saving_throws_notes TEXT,

                            senses_passive_perception INT,
                            senses_passive_investigation INT,
                            senses_passive_insight INT,
                            senses_notes TEXT,

                            defenses TEXT
);

