CREATE SEQUENCE character_seq start 1;

CREATE TABLE characters (
                            character_id SERIAL PRIMARY KEY,
                            character_name VARCHAR NOT NULL,
                            character_level INT NOT NULL,
                            character_active_level BOOLEAN NOT NULL,
                            character_species VARCHAR NOT NULL,
                            character_classes VARCHAR,
                            character_background VARCHAR,
                            character_full_hp INT,
                            character_current_hp INT,
                            character_ac INT,
                            character_initiative VARCHAR,
                            character_hit_dice VARCHAR,
                            character_proficiency VARCHAR,
                            character_bonus VARCHAR,
                            character_ability_saves VARCHAR,
                            character_xp VARCHAR,

                            attribute_strength INT,
                            attribute_strength_mod VARCHAR,
                            attribute_dexterity INT,
                            attribute_dexterity_mod VARCHAR,
                            attribute_constitution INT,
                            attribute_constitution_mod VARCHAR,
                            attribute_intelligence INT,
                            attribute_intelligence_mod VARCHAR,
                            attribute_wisdom INT,
                            attribute_wisdom_mod VARCHAR,
                            attribute_charisma INT,
                            attribute_charisma_mod VARCHAR,

                            skill_acrobatics VARCHAR,
                            skill_acrobatics_mod VARCHAR,
                            skill_acrobatics_prof VARCHAR,
                            skill_animal_handling VARCHAR,
                            skill_animal_handling_mod VARCHAR,
                            skill_animal_handling_prof VARCHAR,
                            skill_arcana VARCHAR,
                            skill_arcana_mod VARCHAR,
                            skill_arcana_prof VARCHAR,
                            skill_athletics VARCHAR,
                            skill_athletics_mod VARCHAR,
                            skill_athletics_prof VARCHAR,
                            skill_deception VARCHAR,
                            skill_deception_mod VARCHAR,
                            skill_deception_prof VARCHAR,
                            skill_history VARCHAR,
                            skill_history_mod VARCHAR,
                            skill_history_prof VARCHAR,
                            skill_insight VARCHAR,
                            skill_insight_mod VARCHAR,
                            skill_insight_prof VARCHAR,
                            skill_intimidation VARCHAR,
                            skill_intimidation_mod VARCHAR,
                            skill_intimidation_prof VARCHAR,
                            skill_investigation VARCHAR,
                            skill_investigation_mod VARCHAR,
                            skill_investigation_prof VARCHAR,
                            skill_medicine VARCHAR,
                            skill_medicine_mod VARCHAR,
                            skill_medicine_prof VARCHAR,
                            skill_nature VARCHAR,
                            skill_nature_mod VARCHAR,
                            skill_nature_prof VARCHAR,
                            skill_perception VARCHAR,
                            skill_perception_mod VARCHAR,
                            skill_perception_prof VARCHAR,
                            skill_performance VARCHAR,
                            skill_performance_mod VARCHAR,
                            skill_performance_prof VARCHAR,
                            skill_persuasion VARCHAR,
                            skill_persuasion_mod VARCHAR,
                            skill_persuasion_prof VARCHAR,
                            skill_religion VARCHAR,
                            skill_religion_mod VARCHAR,
                            skill_religion_prof VARCHAR,
                            skill_sleight_of_hand VARCHAR,
                            skill_sleight_of_hand_mod VARCHAR,
                            skill_sleight_of_hand_prof VARCHAR,
                            skill_stealth VARCHAR,
                            skill_stealth_mod VARCHAR,
                            skill_stealth_prof VARCHAR,
                            skill_survival VARCHAR,
                            skill_survival_mod VARCHAR,
                            skill_survival_prof VARCHAR,

                            proficiencies_armor VARCHAR,
                            proficiencies_weapons VARCHAR,
                            proficiencies_tools VARCHAR,
                            proficiencies_languages VARCHAR,

                            saving_throws_str VARCHAR,
                            saving_throws_str_prof BOOLEAN,
                            saving_throws_dex VARCHAR,
                            saving_throws_dex_prof BOOLEAN,
                            saving_throws_con VARCHAR,
                            saving_throws_con_prof BOOLEAN,
                            saving_throws_int VARCHAR,
                            saving_throws_int_prof BOOLEAN,
                            saving_throws_wis VARCHAR,
                            saving_throws_wis_prof BOOLEAN,
                            saving_throws_cha VARCHAR,
                            saving_throws_cha_prof BOOLEAN,
                            saving_throws_notes VARCHAR,

                            senses_passive_perception INT,
                            senses_passive_investigation INT,
                            senses_passive_insight INT,
                            senses_notes VARCHAR,

                            defenses VARCHAR
);

