INSERT INTO character_spells(
                             character_id,
                             spell_id,
                             learned_spell,
                             active_spell
)

VALUES (
        1,
        289,
        true,
        false
       ),(
          1,
          290,
          true,
          false
       ),(
          1,
          1,
          true,
          false
       ),(
          1,
          291,
          true,
          false
       ),(
          1,
          292,
          true,
          false
       ),(
          1,
          105,
          true,
          false
       ),(
          1,
          293,
          true,
          false
       ),(
          1,
          294,
          true,
          false
       ),(
          1,
          295,
          true,
          false
       ),(
          1,
          296,
          true,
          false
       ),(
          1,
          115,
          true,
          true
       ),(
          1,
          223,
          true,
          false
       ),
       (1,
        136,
        true,
        false
       ),(
          1,
          298,
          true,
          false
       ),(
          1,
          20,
          true,
          false
       ),(
          1,
          221,
          true,
          false
       ),(
          1,
          299,
          true,
          false
       ),(
          1,
          112,
          true,
          false
       ),(
          1,
          4,
          true,
          true
       ),(
          1,
          300,
          true,
          false
       ),(
          1,
          84,
          true,
          false
       ),(
          1,
          301,
          true,
          false
       ),(
          1,
          302,
          true,
          false
       ),(
          1,
          62,
          true,
          false
       ),(
          1,
          303,
          true,
          false
       ),(
          1,
          101,
          true,
          false
       ),(
          1,
          108,
          true,
          false
       ),(
          1,
          304,
          true,
          false
       ),(
          1,
          67,
          true,
          false
       ),(
          1,
          212,
          true,
          false
       ),(
          1,
          305,
          true,
          false
       ),(
          1,
          306,
          true,
          true
       ),(
          1,
          41,
          true,
          true
       ),(
          1,
          307,
          true,
          true
       ),(
          1,
          127,
          true,
          false
       ),(
          1,
          250,
          true,
          false
       ),(
          1,
          308,
          true,
          false
       ),(
          1,
          309,
          true,
          false
       ),(
          1,
          239,
          true,
          false
       ),(
          1,
          269,
          true,
          false
       ),(
          1,
          153,
          true,
          false
       ),(
          1,
          285,
          true,
          false
       ),(
          1,
          310,
          true,
          true
       ),(
          1,
          220,
          true,
          false
       ),(
          1,
          311,
          true,
          false
       ),(
          1,
          312,
          true,
          false
       ),(
          1,
          313,
          true,
          true
       )

